apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apirator.io/v1alpha1",
          "kind": "APIMock",
          "metadata": {
            "name": "example-apimock"
          },
          "spec": {
            "definition": "openapi: \"3.0.0\"\ninfo:\n  title: Simple API overview\n  version: 2.0.0\npaths:\n  /:\n    get:\n      operationId: listVersionsv2\n      summary: List API versions\n      responses:\n        '200':\n          description: |-\n            200 response\n          content:\n            application/json:\n              examples:\n                foo:\n                  value: {\n                    \"versions\": [\n                        {\n                            \"status\": \"CURRENT\",\n                            \"updated\": \"2011-01-21T11:33:21Z\",\n                            \"id\": \"v2.0\",\n                            \"links\": [\n                                {\n                                    \"href\": \"http://127.0.0.1:8774/v2/\",\n                                    \"rel\": \"self\"\n                                }\n                            ]\n                        },\n                        {\n                            \"status\": \"EXPERIMENTAL\",\n                            \"updated\": \"2013-07-23T11:33:21Z\",\n                            \"id\": \"v3.0\",\n                            \"links\": [\n                                {\n                                    \"href\": \"http://127.0.0.1:8774/v3/\",\n                                    \"rel\": \"self\"\n                                }\n                            ]\n                        }\n                    ]\n                 }\n        '300':\n          description: |-\n            300 response\n          content:\n            application/json:\n              examples:\n                foo:\n                  value: |\n                   {\n                    \"versions\": [\n                          {\n                            \"status\": \"CURRENT\",\n                            \"updated\": \"2011-01-21T11:33:21Z\",\n                            \"id\": \"v2.0\",\n                            \"links\": [\n                                {\n                                    \"href\": \"http://127.0.0.1:8774/v2/\",\n                                    \"rel\": \"self\"\n                                }\n                            ]\n                        },\n                        {\n                            \"status\": \"EXPERIMENTAL\",\n                            \"updated\": \"2013-07-23T11:33:21Z\",\n                            \"id\": \"v3.0\",\n                            \"links\": [\n                                {\n                                    \"href\": \"http://127.0.0.1:8774/v3/\",\n                                    \"rel\": \"self\"\n                                }\n                            ]\n                        }\n                    ]\n                   }\n  /v2:\n    get:\n      operationId: getVersionDetailsv2\n      summary: Show API version details\n      responses:\n        '200':\n          description: |-\n            200 response\n          content:\n            application/json:\n              examples:\n                foo:\n                  value: {\n                    \"version\": {\n                      \"status\": \"CURRENT\",\n                      \"updated\": \"2011-01-21T11:33:21Z\",\n                      \"media-types\": [\n                          {\n                              \"base\": \"application/xml\",\n                              \"type\": \"application/vnd.openstack.compute+xml;version=2\"\n                          },\n                          {\n                              \"base\": \"application/json\",\n                              \"type\": \"application/vnd.openstack.compute+json;version=2\"\n                          }\n                      ],\n                      \"id\": \"v2.0\",\n                      \"links\": [\n                          {\n                              \"href\": \"http://127.0.0.1:8774/v2/\",\n                              \"rel\": \"self\"\n                          },\n                          {\n                              \"href\": \"http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf\",\n                              \"type\": \"application/pdf\",\n                              \"rel\": \"describedby\"\n                          },\n                          {\n                              \"href\": \"http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl\",\n                              \"type\": \"application/vnd.sun.wadl+xml\",\n                              \"rel\": \"describedby\"\n                          },\n                          {\n                            \"href\": \"http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl\",\n                            \"type\": \"application/vnd.sun.wadl+xml\",\n                            \"rel\": \"describedby\"\n                          }\n                      ]\n                    }\n                  }\n        '203':\n          description: |-\n            203 response\n          content:\n            application/json:\n              examples:\n                foo:\n                  value: {\n                    \"version\": {\n                      \"status\": \"CURRENT\",\n                      \"updated\": \"2011-01-21T11:33:21Z\",\n                      \"media-types\": [\n                          {\n                              \"base\": \"application/xml\",\n                              \"type\": \"application/vnd.openstack.compute+xml;version=2\"\n                          },\n                          {\n                              \"base\": \"application/json\",\n                              \"type\": \"application/vnd.openstack.compute+json;version=2\"\n                          }\n                      ],\n                      \"id\": \"v2.0\",\n                      \"links\": [\n                          {\n                              \"href\": \"http://23.253.228.211:8774/v2/\",\n                              \"rel\": \"self\"\n                          },\n                          {\n                              \"href\": \"http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf\",\n                              \"type\": \"application/pdf\",\n                              \"rel\": \"describedby\"\n                          },\n                          {\n                              \"href\": \"http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl\",\n                              \"type\": \"application/vnd.sun.wadl+xml\",\n                              \"rel\": \"describedby\"\n                          }\n                      ]\n                    }\n                  }\n",
            "serviceDefinition": {
              "port": 8000,
              "serviceType": "ClusterIP"
            },
            "watch": false
          }
        }
      ]
    capabilities: Basic Install
  name: apirator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: APIMock is the Schema for the apimocks API
      kind: APIMock
      name: apimocks.apirator.io
      version: v1alpha1
  description: Placeholder description
  displayName: Apirator
  install:
    spec:
      deployments:
      - name: apirator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: apirator
          strategy: {}
          template:
            metadata:
              labels:
                app: apirator
                name: apirator
            spec:
              containers:
              - command:
                - apirator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: apirator
                image: apirator/apirator
                imagePullPolicy: Always
                name: apirator
                resources: {}
              serviceAccountName: apirator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resourceNames:
          - apirator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apirator.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: apirator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  replaces: apirator.v0.0.0
  version: 0.0.1
  keywords:
    - apis
    - mocks
    - developer-tools
  maintainers:
    - email: claudioed.oliveira@gmail.com
      name: apirator
  maturity: alpha
  provider:
    name: APIrator
    url: www.apirator.io
