apiVersion: apps/v1
kind: Deployment
metadata:
  name: apirator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apirator
  template:
    metadata:
      labels:
        name: apirator
    spec:
      serviceAccountName: apirator
      containers:
        - name: apirator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - apirator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apirator"
